### ISSUE TITLE
Read eeprom calibration values

### ISSUE THREAD

**Issue by tknopp** [tknopp/RedPitayaDAQServer#10]
from #7 

> We should use the eeprom stuff that is implemented in the regular RP API:
> https://github.com/RedPitaya/RedPitaya/blob/1dfabae67968cc76548e461c7d123a284d3df725/api/src/calib.c
> If that is done the DAC API should use voltage.

In particular I want the "setAmplitude" function to work in Voltage mode. The ADC values should not be converted to float on the RP but rather on the client side. Thus we need to make the scaling/offset values accessible from the client.

**Comment by jonschumacher** [comment]
Should we also use the EEPROM values in the ADC within `readPeriods()`  and `readFrames()` respectively or should this be left in MPIMeasurements and we just save the respective calibration tuple with scale and offset?
