### ISSUE TITLE
Improve the build system

### ISSUE THREAD

**Issue by jbeuke** [tknopp/RedPitayaDAQServer#6]
The build system is currently split into several Makefiles which are invoked by a root folder Makefile and contains absolute paths to libraries. This should be centralized and be made more flexible. A bonus might be to provide different targets for building and installing the server application aswell as the FPGA image.

**Comment by tknopp** [comment]
yes, although this usually is the point where one should ask if `make` is really the right tool for the job. There are modern build systems that are much easier to use.

**Comment by tknopp** [comment]
`cmake` is ok. `qmake` was from perspective a little nicer. Nowadays `Meson` http://mesonbuild.com/index.html seems to get popular. The syntax looks pretty nice.

We jut have to look if these are available in the repository of the debian that is installed on the RP.

**Comment by jbeuke** [comment]
Not only the Debian but also the Alpine Linux which Pavel Demin is now using. But this is the case: https://pkgs.alpinelinux.org/package/edge/main/armhf/meson

But using a different build tool sounds good. I don't really get a grasp on `make`. But thats's something we can do when the rest is working nicely.

**Comment by jbeuke** [comment]
I have just set up a RP completely from scratch. `make` worked flawlessly and I think the FPGA build process now works as well. Can we close this?

**Comment by tknopp** [comment]
I think at this point I don't want so switch the build tools and am fine with the current situation. So yes this can be closed for now.
