### ISSUE TITLE
Error: -113, "Undefined header" when compare package and image versions.

### ISSUE THREAD

**Issue by Astrei** [tknopp/RedPitayaDAQServer#81]
Hello everyone,
I am using freshly installed Julia and the last version of the DAQ server from here. When I try to connect to the RP board, it always gives me a timeout error. In the server log, I found "Error: -113, "Undefined header". I discovered that the error is caused by the command "imgversion(rp)" in RedPitayaDAQServer.jl. When I turn version comparison off, everything works just fine. Can it be an issue with SCPI commands there?

**Comment by jonschumacher** [comment]
I guess I found the reason. The state of the software on `main` is fine but there is no image attached to the latest release. This means you are using an old image which does actually perform as expected (sort of): a mismatch of image and client version is detected. I will attach a matching image when I have time for building one.
