### ISSUE TITLE
Why cann  I  change IP address

### ISSUE THREAD

**Issue by zyh7148** [tknopp/RedPitayaDAQServer#88]

**Comment by nHackel** [comment]
To change the IP you either need to configure a DHCP server that tells the RP which IP to use or you can change the configuration on the RedPitaya.

For that you need to edit [`/etc/dhcpd.conf`](https://github.com/tknopp/RedPitayaDAQServer/blob/e68bedaf93a142abc3810db2eefbbe88ad95d7e7/linux-image/alpine/etc/dhcpcd.conf#L33
). If you set reboot to 0, it will immediately default to a static IP, which you can set in the profile `static_eth0`
