### ISSUE TITLE
Why can't I change the static IP address of DAQServer?

### ISSUE THREAD

**Issue by zyh7148** [tknopp/RedPitayaDAQServer#89]
I login in Apline linux of DAQServer and want to the static IP address by the dhcp file. But after reboot, the IP addresss is reset to the default IP address again. Because 192.168.1.X network address and DHCP server are not used in the customer's network construct, please give me some advice in detail to solve this problem. Thanks!

**Comment by nHackel** [comment]
After you've edited the .conf file you have to commit your changes with `lbu_commit -d`, see the Alpine docs [here](https://wiki.alpinelinux.org/wiki/Alpine_local_backup#Basic_%22commit%22_command)
