### ISSUE TITLE
Range of setPhase

### ISSUE THREAD

**Issue by tknopp** [tknopp/RedPitayaDAQServer#9]
- setPhase expects a value between 0 and 1. This is a little uncommon isn't it?

- Furthermore it would be handy if the phase is considered modulo its range. I do this currently in the client.

**Comment by jbeuke** [comment]
Well it's the factor of 2*pi. This can be arbitrarily changed. What do you think is the better representation: degree or radians? I prefer radians.

**Comment by tknopp** [comment]
radians are fine. lets do that.
